#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2021 Apple Inc. All Rights Reserved.
#
parameters:
  regime: "sparse"
  dataset: "cifar10"
  script: "train_indep.py"
  save_dir: "saved_models/unstructured_sparsity/"
  epochs: 200 # The number of epochs to train for
  batch_size: 128 # Train and test batch sizes
  warmup_budget: 80 # decays topk from 1 to target topk over this percentage of epochs
  test_freq: 20 # Will run test after this many epochs
  learning_rate: 0.1 # Optimizer learning rate
  momentum: 0.9 # Optimizer momentum
  weight_decay: 0.0005 # L2 regularization parameter
  conv_type: "StandardConv" # convolution layer for first layer of network
  bn_type: "StandardGN" # batch norm layer for first layer of network
  block_conv_type: "SparseConv2d" # convolution layer to use for resnet blocks
  block_bn_type: "StandardGN" # batch norm layer to use for resnet blocks
  topk: 0.05 # the target topk to reach after warmup phase. If random_param true, will test at this value
  random_param: True # If true, will train with topk=1 during warmup and then use random topk values
  eval_param_grid: [0.025, 0.05, 0.075, 0.1, 0.125, 0.15, 0.175, 0.2, 0.25, 0.5, 0.75, 0.9, 0.95, 1.0]
  model_config:
    model_class: cpreresnet20
    model_kwargs:
        channel_selection_active: False
