#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2021 Apple Inc. All Rights Reserved.
#
parameters:
  regime: "sparse"
  dataset: "cifar10"
  script: "train_curve.py"
  save_dir: "saved_models/unstructured_sparsity/"
  # Line:
  num_points: 2
  conv_type: "LinesConv" # First convolution layer
  bn_type: "LinesGN" # Batchnorm for first convolution layer
  block_conv_type: "SparseLinesConv" # Convolution layer for ResNet blocks
  block_bn_type: "LinesGN" # Convolution batchnorm layer for ResNet blocks
  epochs: 200 # The number of epochs to train for
  batch_size: 128 # Train and test batch sizes
  warmup_budget: 80 # percentage of epochs for "warmup" phase
  test_freq: 20 # Will run test after this many epochs
  alpha_grid: [0.025, 0.05, 0.075, 0.1, 0.125, 0.15, 0.175, 0.2, 0.25, 0.5, 0.75, 0.9, 0.95, 1.0] # eval at these alphas
  learning_rate: 0.1 # Optimizer learning rate
  momentum: 0.9 # Optimizer momentum
  weight_decay: 0.0005 # L2 regularization parameter
  alpha_sampling: [0.025, 1, 0.50] # Biased endpoint sampling
  model_config:
    model_class: cpreresnet20
    model_kwargs:
      channel_selection_active: False
